notificationTypeID value                                                                                               
------------------ ----------------------------------------------------------------------------------------------------
                 1 like                                                                                                
                 2 dislike                                                                                             
                 3 comment                                                                                             
                 4 subscribe                                                                                           
                 5 post                                                                                                
notificationID recipientUserID senderUserID notificationTypeId isRead createdAt              
-------------- --------------- ------------ ------------------ ------ -----------------------
EmojiShowID emojiName                                                                                            videoID     ClickCounter
----------- ---------------------------------------------------------------------------------------------------- ----------- ------------
         11 Happy                                                                                                          1            5
         12 Laugh                                                                                                          2           10
         13 Love                                                                                                           3            8
         14 Cool                                                                                                           4            3
         15 Cry                                                                                                            5            7
         16 Angry                                                                                                          6            2
         17 ThumbsUp                                                                                                       7           12
         18 ThumbsDown                                                                                                     8            4
         19 Heart                                                                                                          9           15
         20 Fire                                                                                                          10            6
promoCodeID codeValue            isUsed balance              
----------- -------------------- ------ ---------------------
PaymentID   CardNumber       ExpirationDate   CardholderName                                                                                                                                                                                                                                                  Amount                TransactionDate         userID     
----------- ---------------- ---------------- --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- --------------------- ----------------------- -----------
name                                                                                                                             principal_id diagram_id  version     definition
-------------------------------------------------------------------------------------------------------------------------------- ------------ ----------- ----------- ----------
membershipID userID      startDate               endDate                 createdAt               isActive
------------ ----------- ----------------------- ----------------------- ----------------------- --------
videoStatisticsId videoID     clickCounter
----------------- ----------- ------------
typeID      type                
----------- --------------------
          1 admin               
          2 user                
          3 superuser           
          4 guest               
userID      name                 surname              userName                                           birthDate        profilePicture country                                            subscriberCount typeID     
----------- -------------------- -------------------- -------------------------------------------------- ---------------- -------------- -------------------------------------------------- --------------- -----------
          1 Irman                Isic                 irman99                                                  1999-12-27 NULL           Bosnia and Herzegovina                                        1000           1
          2 azer                 pilavdzic            azer123                                                  2000-09-26 NULL           Bosnia and Herzegovina                                         300           1
userValuesID userID      email                                                                            password                                           passwordHash                                                    
------------ ----------- -------------------------------------------------------------------------------- -------------------------------------------------- ----------------------------------------------------------------
categoryID  categoryName                                      
----------- --------------------------------------------------
          1 Entertainment                                     
          2 Food                                              
          3 Gaming                                            
          4 Beauty and Fashion                                
          5 Music                                             
          6 Science and Technology                            
          7 Travel                                            
videoID     videoName                                                                                                                                                                                                                                                       filePath                                                                                                                                                                                                                                                         description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          resolutionType uploadDate              durationInSecondes isFree userID      categoryID 
----------- --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- -------------- ----------------------- ------------------ ------ ----------- -----------
          1 Enter the savage kingdom - wildlife LIVE                                                                                                                                                                                                                        https://www.youtube.com/watch?v=BJ3Yv572V1A                                                                                                                                                                                                                      Ruthless predators and powerful prey are embroiled in rivalry, betrayal, and battle, in a never-ending crusade for survival, with characters so wild and ambitious and conflict so cutthroat, that no diction can do it justice. Each episode presents the battle from one characters point of view exposing the front lines of clan warfare— from a mothers sacrifice to a fathers rage at his own son                                                                                                              FULL_HD        2024-09-04 23:01:04.123                120      1           1           1
          2 The Ultimate Guide to Street Food                                                                                                                                                                                                                               https://www.youtube.com/watch?v=123abc                                                                                                                                                                                                                           Join us as we explore the hidden gems of street food around the world, showcasing mouth-watering dishes, unique flavors, and the vibrant cultures that create them.                                                                                                                                                                                                                                                                                                                                                  FULL_HD        2024-09-04 23:04:27.463                 30      1           1           2
          3 Top 10 Gaming Moments of All Time                                                                                                                                                                                                                               https://www.youtube.com/watch?v=456def                                                                                                                                                                                                                           From legendary eSports moments to game-breaking glitches, these are the top 10 gaming moments that will forever be etched in history.                                                                                                                                                                                                                                                                                                                                                                                FULL_HD        2024-09-04 23:04:27.463                 25      1           1           3
          4 Exploring the Future of AI and Robotics                                                                                                                                                                                                                         https://www.youtube.com/watch?v=789ghi                                                                                                                                                                                                                           Discover how cutting-edge AI and robotics are reshaping industries and what the future holds for humanity in this technological revolution.                                                                                                                                                                                                                                                                                                                                                                          FULL_HD        2024-09-04 23:04:27.463                 45      1           1           6
          5 The Ultimate Fashion Trends for 2024                                                                                                                                                                                                                            https://www.youtube.com/watch?v=101jkl                                                                                                                                                                                                                           Step into the world of high fashion as we unveil the biggest trends that are taking over the runway in 2024. From bold colors to unique textures, get ready for a fashion revolution.                                                                                                                                                                                                                                                                                                                                FULL_HD        2024-09-04 23:04:27.463                 15      1           1           4
          6 Top Travel Destinations of 2024                                                                                                                                                                                                                                 https://www.youtube.com/watch?v=112mno                                                                                                                                                                                                                           Pack your bags and get ready to explore the top travel destinations of 2024! From hidden gems to popular tourist spots, we have you covered.                                                                                                                                                                                                                                                                                                                                                                         FULL_HD        2024-09-04 23:04:27.463                 40      1           1           7
          7 Top 10 Iconic Music Hits of the 90s                                                                                                                                                                                                                             https://www.youtube.com/watch?v=113pqr                                                                                                                                                                                                                           Relive the golden era of music as we count down the top 10 iconic hits from the 90s that changed the music industry forever.                                                                                                                                                                                                                                                                                                                                                                                         FULL_HD        2024-09-04 23:04:27.463                 20      1           1           5
          8 Inside the World of Virtual Reality Entertainment                                                                                                                                                                                                               https://www.youtube.com/watch?v=114stu                                                                                                                                                                                                                           Explore the rapidly expanding world of virtual reality entertainment. From gaming to interactive experiences, VR is changing how we consume media.                                                                                                                                                                                                                                                                                                                                                                   FULL_HD        2024-09-04 23:04:27.463                 35      1           1           1
          9 Mastering the Art of Italian Cuisine                                                                                                                                                                                                                            https://www.youtube.com/watch?v=abc123                                                                                                                                                                                                                           Learn how to prepare authentic Italian dishes from scratch, from pasta to pizza, with tips from world-renowned chefs.                                                                                                                                                                                                                                                                                                                                                                                                FULL_HD        2024-09-04 23:06:47.483                 50      1           1           2
         10 Top 10 Open World Games in 2024                                                                                                                                                                                                                                 https://www.youtube.com/watch?v=def456                                                                                                                                                                                                                           Explore the vast and immersive open-world games releasing in 2024, featuring stunning landscapes, compelling narratives, and endless gameplay.                                                                                                                                                                                                                                                                                                                                                                       FULL_HD        2024-09-04 23:06:47.483                 35      1           1           3
         11 The Beauty Secrets You Need to Know                                                                                                                                                                                                                             https://www.youtube.com/watch?v=ghi789                                                                                                                                                                                                                           Uncover the top beauty hacks and fashion tips from the industry experts, and elevate your personal style.                                                                                                                                                                                                                                                                                                                                                                                                            FULL_HD        2024-09-04 23:06:47.483                 25      1           1           4
         12 Music Legends: The Story Behind the Hits                                                                                                                                                                                                                        https://www.youtube.com/watch?v=jkl101                                                                                                                                                                                                                           Dive into the history of music’s greatest hits and discover how these legendary tracks came to be, from inception to worldwide success.                                                                                                                                                                                                                                                                                                                                                                              FULL_HD        2024-09-04 23:06:47.483                 40      1           1           5
         13 The Future of Space Exploration                                                                                                                                                                                                                                 https://www.youtube.com/watch?v=mno112                                                                                                                                                                                                                           Explore the latest advancements in space technology and discover how humanity is preparing for interplanetary travel in the near future.                                                                                                                                                                                                                                                                                                                                                                             FULL_HD        2024-09-04 23:06:47.483                 55      1           1           6
         14 Adventure in the Amazon Rainforest                                                                                                                                                                                                                              https://www.youtube.com/watch?v=pqr113                                                                                                                                                                                                                           Join us as we embark on an epic journey through the Amazon rainforest, uncovering its hidden wonders and exotic wildlife.                                                                                                                                                                                                                                                                                                                                                                                            FULL_HD        2024-09-04 23:06:47.483                 60      1           1           7
         15 The Ultimate Entertainment Experience                                                                                                                                                                                                                           https://www.youtube.com/watch?v=stu114                                                                                                                                                                                                                           Discover the best in entertainment, from movies to live shows, and everything in between in this comprehensive entertainment guide.                                                                                                                                                                                                                                                                                                                                                                                  FULL_HD        2024-09-04 23:06:47.483                 45      1           1           1
         16 The Science of Climate Change                                                                                                                                                                                                                                   https://www.youtube.com/watch?v=vwx115                                                                                                                                                                                                                           Understand the science behind climate change, its impact on the world, and what steps we can take to combat it.                                                                                                                                                                                                                                                                                                                                                                                                      FULL_HD        2024-09-04 23:06:47.483                 30      1           1           6
         17 Epic Travel Adventures: Across the Globe                                                                                                                                                                                                                        https://www.youtube.com/watch?v=yzx116                                                                                                                                                                                                                           Join us as we travel to some of the world’s most exotic locations, from the deserts of Africa to the islands of the Pacific.                                                                                                                                                                                                                                                                                                                                                                                         FULL_HD        2024-09-04 23:06:47.483                 70      1           1           7
         18 Behind the Scenes of eSports Tournaments                                                                                                                                                                                                                        https://www.youtube.com/watch?v=abx117                                                                                                                                                                                                                           Go behind the scenes of the world’s biggest eSports tournaments and meet the pro players competing for the championship titles.                                                                                                                                                                                                                                                                                                                                                                                      FULL_HD        2024-09-04 23:06:47.483                 40      1           1           3
         19 Exploring Street Food in Asia                                                                                                                                                                                                                                   https://www.youtube.com/watch?v=abc333                                                                                                                                                                                                                           A journey through Asia’s best street food.                                                                                                                                                                                                                                                                                                                                                                                                                                                                           FULL_HD        2024-09-04 23:50:34.640                 20      1           1           2
         20 Top 10 Indie Games 2024                                                                                                                                                                                                                                         https://www.youtube.com/watch?v=def444                                                                                                                                                                                                                           Discover the top indie games coming in 2024.                                                                                                                                                                                                                                                                                                                                                                                                                                                                         FULL_HD        2024-09-04 23:50:34.640                 35      1           1           3
         21 How to Style for Summer 2024                                                                                                                                                                                                                                    https://www.youtube.com/watch?v=ghi555                                                                                                                                                                                                                           Get the latest summer fashion trends for 2024.                                                                                                                                                                                                                                                                                                                                                                                                                                                                       FULL_HD        2024-09-04 23:50:34.640                 15      1           1           4
         22 Best Concerts of the Year                                                                                                                                                                                                                                       https://www.youtube.com/watch?v=jkl666                                                                                                                                                                                                                           Relive the best concerts of 2024.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    FULL_HD        2024-09-04 23:50:34.640                 40      1           1           5
         23 The Rise of AI in Healthcare                                                                                                                                                                                                                                    https://www.youtube.com/watch?v=mno777                                                                                                                                                                                                                           How AI is transforming the healthcare industry.                                                                                                                                                                                                                                                                                                                                                                                                                                                                      FULL_HD        2024-09-04 23:50:34.640                 50      1           1           6
         24 Hidden Gems of Europe                                                                                                                                                                                                                                           https://www.youtube.com/watch?v=pqr888                                                                                                                                                                                                                           Explore hidden travel gems across Europe.                                                                                                                                                                                                                                                                                                                                                                                                                                                                            FULL_HD        2024-09-04 23:50:34.640                 60      1           1           7
thumbnailInfoID thumbnailPicture videoID    
--------------- ---------------- -----------
commentID   userID      videoID     content                                                                                                                                                                                                                                                                                                      postedDate             
----------- ----------- ----------- ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ -----------------------
ratingID    videoID     likeCount   dislikeCount
----------- ----------- ----------- ------------
ratingID    commentID   likeCount   dislikeCount
----------- ----------- ----------- ------------
playlistID  userID      playlistName                                       isPublic
----------- ----------- -------------------------------------------------- --------
          1           1 Epic Travel Adventures                                    1
          2           2 Gaming Highlights                                         0
          3           1 Top Food Recipes                                          1
          4           2 Science and Tech Innovations                              1
          5           1 Fashion Trends 2024                                       0
          6           2 Best Entertainment Moments                                1
          7           1 Music Legends Collection                                  1
          8           2 VR and Gaming Experience                                  0
          9           1 Explore the World                                         1
         10           2 Tech Innovations Playlist                                 0
playlistID  videoID    
----------- -----------
          1           7
          1          10
          1          16
          2           3
          2           8
          2          12
          3           2
          3          11
          4           6
          4          14
          5           4
          5          13
          6           1
          6          15
          7           5
          7           9
          8           8
          8          12
          9           7
          9          10
          9          16
         10           6
         10          14
advertisementID userID      videoID     advertisementPictureURL                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
--------------- ----------- ----------- --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
              2           2           2 https://i.ytimg.com/vi/emmXWi4iAW4/maxresdefault.jpg                                                                                                                                                                                                                                                                                                                                                                                                                                                                
              3           2           4 https://imageio.forbes.com/specials-images/imageserve/628b8de7a18d8436b8782e88/0x0.jpg?format=jpg&height=600&width=1200&fit=bounds                                                                                                                                                                                                                                                                                                                                                                                  
              4           2           2 https://i.ytimg.com/vi/emmXWi4iAW4/maxresdefault.jpg                                                                                                                                                                                                                                                                                                                                                                                                                                                                
              5           2           4 https://imageio.forbes.com/specials-images/imageserve/628b8de7a18d8436b8782e88/0x0.jpg?format=jpg&height=600&width=1200&fit=bounds                                                                                                                                                                                                                                                                                                                                                                                  
              6           2           2 https://i.ytimg.com/vi/emmXWi4iAW4/maxresdefault.jpg                                                                                                                                                                                                                                                                                                                                                                                                                                                                
              7           2           4 https://imageio.forbes.com/specials-images/imageserve/628b8de7a18d8436b8782e88/0x0.jpg?format=jpg&height=600&width=1200&fit=bounds                                                                                                                                                                                                                                                                                                                                                                                  
              8           1           5 https://cdn.pixabay.com/photo/2016/11/14/03/16/advertisement-1820919_960_720.jpg                                                                                                                                                                                                                                                                                                                                                                                                                                    
              9           2           7 https://i.ytimg.com/vi/abcd1234/maxresdefault.jpg                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
             10           1           8 https://www.advertisementjpg.com/wp-content/uploads/2021/07/Adver-600x400.jpg                                                                                                                                                                                                                                                                                                                                                                                                                                       
             11           2           9 https://cdn.pixabay.com/photo/2018/02/10/21/44/advertisement-3146411_960_720.jpg                                                                                                                                                                                                                                                                                                                                                                                                                                    
             12           1          11 https://upload.wikimedia.org/wikipedia/commons/1/1e/Ad-image.png                                                                                                                                                                                                                                                                                                                                                                                                                                                    
             13           2          13 https://www.advertisehere.com/advertise.jpg                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
             14           1          14 https://i.ytimg.com/vi/xyz45678/maxresdefault.jpg                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
             15           2          15 https://example.com/adver_pic_large.jpg                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
             16           1          16 https://cdn.pixabay.com/photo/2020/05/22/10/15/advertisement-5204925_960_720.jpg                                                                                                                                                                                                                                                                                                                                                                                                                                    
             17           2          10 https://upload.wikimedia.org/wikipedia/commons/9/9d/Ad-sample.jpg                                                                                                                                                                                                                                                                                                                                                                                                                                                   
sessionTableID userID      videoID     timeStamp  
-------------- ----------- ----------- -----------
walletID    balance               userID     
----------- --------------------- -----------
transactionID userID      dateOfTransaction       transactionAmount     transactionStatus
------------- ----------- ----------------------- --------------------- -----------------
ReportTypeID Type                                              
------------ --------------------------------------------------
           1 misinformation                                    
           2 copyright                                         
           3 spam                                              
           4 hate speech                                       
reportID    userID      videoID     reportTypeId reportText                                                                                                                                             dateOfReport           
----------- ----------- ----------- ------------ ------------------------------------------------------------------------------------------------------------------------------------------------------ -----------------------
          1           1           5            1 This video contains misleading information about the topic.                                                                                            2024-09-04 23:53:18.800
          2           2           9            2 The video is using copyrighted material without permission.                                                                                            2024-09-04 23:53:18.800
          3           1           7            3 This video is filled with spam links in the comments and description.                                                                                  2024-09-04 23:53:18.800
          4           2           3            4 The video contains hate speech targeting specific groups.                                                                                              2024-09-04 23:53:18.800
          5           1          12            1 This video is spreading false claims that can mislead viewers.                                                                                         2024-09-04 23:53:18.800
          6           2          16            2 The video promotes content that infringes on copyrights.                                                                                               2024-09-04 23:53:18.800
messagebodyID msgSenderID msgRecieverID body                                                                                                                                                                                                                                                            timeSent                seen
------------- ----------- ------------- --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- ----------------------- ----
supportID   userID      body                                                                                                                                                                                                                                                            timeSent                seen
----------- ----------- --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- ----------------------- ----
GroupID     SyncOwnerID VideoID     GroupCode 
----------- ----------- ----------- ----------
          1           1           3 abc123    
GroupMemberID GroupID     UserID     
------------- ----------- -----------
            1           1           1
            2           1           2
blogID      userID      title                                              pictureURL                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           content                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
----------- ----------- -------------------------------------------------- -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
          1           2 title for blog number 1                            https://img.freepik.com/free-photo/teamwork-making-online-blog_53876-94868.jpg?                                                                                                                                                                                                                                                                                                                                                                                                                                      this is content for blog no1.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
          2           2 title for blog number 2                            https://img.freepik.com/free-photo/technology-communication-icons-symbols-concept_53876-120314.jpg                                                                                                                                                                                                                                                                                                                                                                                                                   this is content for blog no2.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
          4           2 title for blog number 3                            https://img.freepik.com/free-photo/digital-marketing-media-technology-concept_53876-120315.jpg                                                                                                                                                                                                                                                                                                                                                                                                                       this is content for blog no3.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
          5           2 title for blog number 4                            https://img.freepik.com/free-photo/creative-process-ideas-innovation-technology_53876-120316.jpg                                                                                                                                                                                                                                                                                                                                                                                                                     this is content for blog no4.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
          6           2 title for blog number 5                            https://img.freepik.com/free-photo/music-notes-symbol-tech-background_53876-120317.jpg                                                                                                                                                                                                                                                                                                                                                                                                                               this is content for blog no5.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
          7           2 title for blog number 6                            https://img.freepik.com/free-photo/science-research-symbols-icons-background_53876-120318.jpg                                                                                                                                                                                                                                                                                                                                                                                                                        this is content for blog no6.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
          8           2 title for blog number 7                            https://img.freepik.com/free-photo/travel-symbols-concept-icons-background_53876-120319.jpg                                                                                                                                                                                                                                                                                                                                                                                                                          this is content for blog no7.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
          9           2 title for blog number 8                            https://img.freepik.com/free-photo/entertainment-symbols-background-concept_53876-120320.jpg                                                                                                                                                                                                                                                                                                                                                                                                                         this is content for blog no8.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
         10           2 title for blog number 9                            https://img.freepik.com/free-photo/delicious-food-cuisine-symbols_53876-120321.jpg                                                                                                                                                                                                                                                                                                                                                                                                                                   this is content for blog no9.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
         11           2 title for blog number 10                           https://img.freepik.com/free-photo/gaming-symbol-tech-background_53876-120322.jpg                                                                                                                                                                                                                                                                                                                                                                                                                                    this is content for blog no10.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
         12           2 title for blog number 11                           https://img.freepik.com/free-photo/fashion-symbols-concept-background_53876-120323.jpg                                                                                                                                                                                                                                                                                                                                                                                                                               this is content for blog no11.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
         13           2 title for blog number 12                           https://img.freepik.com/free-photo/music-symbol-tech-background-concept_53876-120324.jpg                                                                                                                                                                                                                                                                                                                                                                                                                             this is content for blog no12.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
         14           2 title for blog number 13                           https://img.freepik.com/free-photo/science-research-icons-symbols-background_53876-120325.jpg                                                                                                                                                                                                                                                                                                                                                                                                                        this is content for blog no13.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
         15           2 title for blog number 14                           https://img.freepik.com/free-photo/exploring-new-travel-destinations-concept_53876-120326.jpg                                                                                                                                                                                                                                                                                                                                                                                                                        this is content for blog no14.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
         16           2 title for blog number 15                           https://img.freepik.com/free-photo/entertainment-symbol-icons-background-concept_53876-120327.jpg                                                                                                                                                                                                                                                                                                                                                                                                                    this is content for blog no15.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
